name: Functions

# To run this workflow's tests locally, see ./hack/test-full.sh

permissions:
  id-token: write   # Required for signing
  contents: read
  packages: write
  attestations: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and Publish
  publish-utils-image:
    name: Publish Utils Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: knative/actions/setup-go@main
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build Images
#        run: |
#          for a in amd64 arm64 ppc64le s390x; do
#            CGO_ENABLED=0 GOARCH="${a}" go build -o "func-util-$a" -trimpath -ldflags '-w -s' ./cmd/func-util
#          done
      - name: Build Images
        id: build-images
        run: |
          export SOURCE_DATE_EPOCH=0
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx build . -f Dockerfile.utils \
            --output type=image,rewrite-timestamp=true \
            --provenance=false --sbom=false \
            --platform=linux/ppc64le,linux/s390x,linux/amd64,linux/arm64 \
            --push \
            -t "ghcr.io/matejvasek/func-utils:v2" \
            --annotation index:org.opencontainers.image.description="Knative Func Utils Image" \
            --annotation index:org.opencontainers.image.source="https://github.com/knative/func" \
            --annotation index:org.opencontainers.image.vendor="https://github.com/knative/func" \
            --annotation index:org.opencontainers.image.url="https://github.com/knative/func/pkgs/container/func-utils" \
            --metadata-file build-metadata.json
          DIGEST=$(jq -r '."containerimage.digest"' build-metadata.json)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: "ghcr.io/matejvasek/func-utils"
          subject-digest: ${{ steps.build-images.outputs.digest }}
          push-to-registry: true
