name: Update Quarkus Platform in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    name: Update Quarkus Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install xmllint
        run: sudo apt -y install libxml2-utils
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./hack/update-quarkus-platform.sh

