name: Func E2E OnCluster Test

on: [pull_request]

jobs:
  test:
    name: On Cluster Test
    strategy:
      matrix:
        go: [1.18.x]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    env:
      FUNC_OPENSHIFT_ENABLED: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Install Binaries
        run: ./hack/binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Deploy Tekton
        run: ./hack/tekton.sh
      - name: Deploy Test Git Server
        run: ./test/gitserver.sh
      - name: E2E On Cluster Test
        env:
          E2E_RUNTIMES: ""
        run: make && make test-e2e-on-cluster
