name: Func Unit Test

on:
  push:
    branches:
      - "debug-win"

jobs:
  test:
    name: Unit Test Debug
    strategy:
      matrix:
        go: [1.16.x]
        java: [11]
        os: ["windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Bash 4 on Mac
        if: matrix.os == 'macos-latest'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

          brew install bash
          brew install gnu-sed

          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: A
        run: hostname
      - name: B
        run: ipconfig
      - name: Core Unit Tests
        run: make test
