name: Update Quarkus Platform in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update:
    name: Update Quarkus Platform
    runs-on: ubuntu-latest
    steps:
      - name: Setup Babashka
        run: curl -L -s https://github.com/babashka/babashka/releases/download/v0.9.161/babashka-0.9.161-linux-amd64-static.tar.gz | sudo tar -zxf - > /usr/bin/bb && sudo chmod +x /usr/bin/bb
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bb ./hack/update-quarkus-platform.clj

