name: Update Quarkus Platform in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  push:
    #  schedule:
    #    - cron: '*/15 * * * *'

jobs:
  update:
    name: Update Quarkus Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install NPM deps.
        run: npm install axios xml2js octokit --location=global
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node ./hack/update-quarkus-platform.js

