name: Update Builder Image

on:
  push:
    branches:
      - "custom-builder-2"

jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"
      - name: Build and Push
        env:
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ github.token }}
        run: go run ./hack/update-builder.go
